import { Job } from "../../../interfaces/job";

const JobListData: Array<Job> = [
  {
    _id: "92e5bafc-90f0-4a13-8478-6e8f306d3111",
    title: "Mechanic",
    companyName: "AutoFix Cameroon",
    location: "Douala, Cameroon",
    employmentType: "FULL_TIME",
    deadline: "October 29, 2024",
    salaryRange: "100,000 XAF",
    experienceLevel: "0-2 years",
    description:
      "We are seeking a dynamic and experienced Finance Executive to join our team...",
    qualifications: [
      "2 years of experience in finance",
      "Proficiency in Excel and Word",
      "Strong communication skills",
    ],
    skills: ["Accounting", "Time Management", "Teamwork"],
    benefits: ["Health Insurance", "Flexible working hours", "Company Car"],
    languageRequirements: "English, French",
  },
  {
    _id: "0582b5ec-cf10-4935-99af-ca31b9caed62",
    title: "Plumber",
    companyName: "PlumbTech Cameroon",
    location: "Yaounde, Cameroon",
    employmentType: "FULL_TIME",
    deadline: "November 1, 2024",
    salaryRange: "80,000 XAF",
    experienceLevel: "2-5 years",
    description:
      "We are seeking a dynamic and experienced Finance Executive to join our team...",
    qualifications: [
      "2 years of experience in finance",
      "Proficiency in Excel and Word",
      "Strong communication skills",
    ],
    skills: ["Accounting", "Time Management", "Teamwork"],
    benefits: ["Health Insurance", "Flexible working hours", "Company Car"],
    languageRequirements: "English, French",
  },
  {
    _id: "dd073b82-a339-47aa-9bdf-4d43008e66af",
    title: "Electrician",
    companyName: "Power Services Cameroon",
    location: "Bamenda, Cameroon",
    employmentType: "FULL_TIME",
    deadline: "October 31, 2024",
    salaryRange: "90,000 XAF",
    experienceLevel: "5+ years",
    description:
      "We are seeking a dynamic and experienced Finance Executive to join our team...",
    qualifications: [
      "2 years of experience in finance",
      "Proficiency in Excel and Word",
      "Strong communication skills",
    ],
    skills: ["Accounting", "Time Management", "Teamwork"],
    benefits: ["Health Insurance", "Flexible working hours", "Company Car"],
    languageRequirements: "English, French",
  },
  {
    _id: "8ad75815-7488-4ab0-bb8c-c0220e07e067",
    title: "Tailor",
    companyName: "Cameroonian Fashion House",
    location: "Bafoussam, Cameroon",
    employmentType: "FULL_TIME",
    deadline: "November 5, 2024",
    salaryRange: "60,000 XAF",
    experienceLevel: "0-2 years",
    description:
      "We are seeking a dynamic and experienced Finance Executive to join our team...",
    qualifications: [
      "2 years of experience in finance",
      "Proficiency in Excel and Word",
      "Strong communication skills",
    ],
    skills: ["Accounting", "Time Management", "Teamwork"],
    benefits: ["Health Insurance", "Flexible working hours", "Company Car"],
    languageRequirements: "English, French",
  },
  {
    _id: "67351462-bb9d-4629-90b7-9f5de12060e5",
    title: "Carpenter",
    companyName: "WoodCraft Cameroon",
    location: "Douala, Cameroon",
    employmentType: "CONTRACT",
    deadline: "October 25, 2024",
    salaryRange: "95,000 XAF",
    experienceLevel: "2-5 years",
    description:
      "We are seeking a dynamic and experienced Finance Executive to join our team...",
    qualifications: [
      "2 years of experience in finance",
      "Proficiency in Excel and Word",
      "Strong communication skills",
    ],
    skills: ["Accounting", "Time Management", "Teamwork"],
    benefits: ["Health Insurance", "Flexible working hours", "Company Car"],
    languageRequirements: "English, French",
  },
  {
    _id: "94bcf585-7064-4ec7-bc76-73d7f8b93f23",
    title: "Painter",
    companyName: "ColorWave Cameroon",
    location: "Garoua, Cameroon",
    employmentType: "FULL_TIME",
    deadline: "November 2, 2024",
    salaryRange: "85,000 XAF",
    experienceLevel: "0-2 years",
    description:
      "We are seeking a dynamic and experienced Finance Executive to join our team...",
    qualifications: [
      "2 years of experience in finance",
      "Proficiency in Excel and Word",
      "Strong communication skills",
    ],
    skills: ["Accounting", "Time Management", "Teamwork"],
    benefits: ["Health Insurance", "Flexible working hours", "Company Car"],
    languageRequirements: "English, French",
  },
  {
    _id: "07e69764-1caf-40f8-857a-c744069f5d26",
    title: "Housekeeper",
    companyName: "Hotel Resort",
    location: "Limbe, Cameroon",
    employmentType: "FULL_TIME",
    deadline: "October 28, 2024",
    salaryRange: "70,000 XAF",
    experienceLevel: "0-2 years",
    description:
      "We are seeking a dynamic and experienced Finance Executive to join our team...",
    qualifications: [
      "2 years of experience in finance",
      "Proficiency in Excel and Word",
      "Strong communication skills",
    ],
    skills: ["Accounting", "Time Management", "Teamwork"],
    benefits: ["Health Insurance", "Flexible working hours", "Company Car"],
    languageRequirements: "English, French",
  },
  {
    _id: "3ffe4b12-5376-4c5e-8f64-da2c33ec0f34",
    title: "Welder",
    companyName: "IronWorks Cameroon",
    location: "Kumba, Cameroon",
    employmentType: "CONTRACT",
    deadline: "November 6, 2024",
    salaryRange: "110,000 XAF",
    experienceLevel: "5+ years",
    description:
      "We are seeking a dynamic and experienced Finance Executive to join our team...",
    qualifications: [
      "2 years of experience in finance",
      "Proficiency in Excel and Word",
      "Strong communication skills",
    ],
    skills: ["Accounting", "Time Management", "Teamwork"],
    benefits: ["Health Insurance", "Flexible working hours", "Company Car"],
    languageRequirements: "English, French",
  },
  {
    _id: "a75ba6b3-3aa7-43a3-a066-dfae9ee27431",
    title: "Driver",
    companyName: "LogisticsPro",
    location: "Bertoua, Cameroon",
    employmentType: "FULL_TIME",
    deadline: "October 27, 2024",
    salaryRange: "75,000 XAF",
    experienceLevel: "0-2 years",
    description:
      "We are seeking a dynamic and experienced Finance Executive to join our team...",
    qualifications: [
      "2 years of experience in finance",
      "Proficiency in Excel and Word",
      "Strong communication skills",
    ],
    skills: ["Accounting", "Time Management", "Teamwork"],
    benefits: ["Health Insurance", "Flexible working hours", "Company Car"],
    languageRequirements: "English, French",
  },
  {
    _id: "c5b85218-be6a-4af6-9759-b51a9a53cb2d",
    title: "Barber",
    companyName: "HairMasters",
    location: "Douala, Cameroon",
    employmentType: "PART_TIME",
    deadline: "October 26, 2024",
    salaryRange: "50,000 XAF",
    experienceLevel: "0-2 years",
    description:
      "We are seeking a dynamic and experienced Finance Executive to join our team...",
    qualifications: [
      "2 years of experience in finance",
      "Proficiency in Excel and Word",
      "Strong communication skills",
    ],
    skills: ["Accounting", "Time Management", "Teamwork"],
    benefits: ["Health Insurance", "Flexible working hours", "Company Car"],
    languageRequirements: "English, French",
  },
];

export {
  JobListData,
}